# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Documentation CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set Up Cache
      uses: actions/cache@v2.0.0
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create Documentation
      run: ./gradlew dokkaHtml
    - run: |
        mv build/dokka/html/-butterfly build/dokka/html/butterfly
        chmod -R +777 build/dokka
    - name: Push to docs server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_IP }}
        port: 22
        debug: true
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASS }}
        source: "build/dokka/html/butterfly,build/dokka/html/image,build/dokka/html/scripts,build/dokka/html/styles,build/dokka/html/-search.html,build/dokka/html/navigation.html"
        target: "/var/www/docs.augu.dev/dist"
        overwrite: true
        strip_components: 2
        tar_tmp_path: /tmp/kotlin-docs
#     - name: Move from kotlin-docs to location
#       uses: appleboy/ssh-action@master
#       with:
#         # ssh host
#         host: ${{ secrets.REMOTE_IP }}
#         username: ${{ secrets.REMOTE_USER }}
#         password: ${{ secrets.REMOTE_PASS }}
#         script: |
#           cp ~/kotlin-docs/* /var/www/docs.augu.dev/dist
