# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Documentation CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create Documentation
      run: ./gradlew dokka
    - run: mv build/dokka/-butterfly build/dokka/butterfly
    - name: Push to docs server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_IP }}
        port: 22
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASS }}
        source: "build/dokka/butterfly,build/dokka/style.css"
        target: "~/kotlin-docs"
        override: true
        strip_components: 2
