# This is a basic workflow to help you get started with Actions

name: Documentation Stable CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ stable ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set Up Cache
      uses: actions/cache@v2.0.0
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create Documentation
      run: ./gradlew dokkaHtml
    - name: Give Permissions
      run: chmod -R +777 build/dokka
    - name: Push to docs server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_IP }}
        port: 22
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASS }}
        source: "build/dokka/html/*"
        target: "/var/www/docs.augu.dev/dist/stable"
        overwrite: true
        strip_components: 3
        tar_tmp_path: /tmp/kotlin-docs
#     - name: Move from kotlin-docs to location
#       uses: appleboy/ssh-action@master
#       with:
#         # ssh host
#         host: ${{ secrets.REMOTE_IP }}
#         username: ${{ secrets.REMOTE_USER }}
#         password: ${{ secrets.REMOTE_PASS }}
#         script: |
#           cp ~/kotlin-docs/* /var/www/docs.augu.dev/dist

