name: Gradle Package

on:
  release:
    types: [created]
    branches:
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build with Gradle
      run: gradlew build
    - name: Publish to Bintray
      run: gradlew bintrayUpload
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
